name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 6.0.x  # Schimbă versiunea dacă folosești alta (ex. 7.0.x)

      - name: Display .NET version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore BlazorApp/BlazorApp.sln  # Modifică cu calea corectă

      - name: Build project
        run: dotnet build BlazorApp/BlazorApp.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test BlazorApp/BlazorApp.sln --configuration Release --no-restore --verbosity normal

      - name: Publish application
        run: dotnet publish BlazorApp/BlazorApp.sln --configuration Release --no-restore --output publish/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish/
